spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB        # 单个文件最大 5M
      max-request-size: 10MB    # 总请求最大 10M
  datasource:
    url: jdbc:mysql://localhost:3306/logistics_eval?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: 你的用户名
    password: 你的密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

# 自定义图片存储路径
app:
  upload:
    path: ./upload/images/   # 相对路径，项目根目录下

kind: Application
